language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 2f0eeda8d88398eb5a1ede4e0ed308ad8b1dc20cdb00c6d40c187ece1d0b4db5
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
